// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3dv7sDJosAJrC-1vFP_XbGaH_oGLoWFk',
    appId: '1:345359008700:web:3550b37027fa26c36a21b9',
    messagingSenderId: '345359008700',
    projectId: 'mindchoisestestapp',
    authDomain: 'mindchoisestestapp.firebaseapp.com',
    storageBucket: 'mindchoisestestapp.firebasestorage.app',
    measurementId: 'G-GJVNJF2RF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu5abJjaB0OxItHB5LK-NaaAFyyRZxvOE',
    appId: '1:345359008700:android:c62a0039093b7c046a21b9',
    messagingSenderId: '345359008700',
    projectId: 'mindchoisestestapp',
    storageBucket: 'mindchoisestestapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD9frbDlesnpCkfFKXiNC7x71iSPObUnU',
    appId: '1:345359008700:ios:ca8b0532f4c01f316a21b9',
    messagingSenderId: '345359008700',
    projectId: 'mindchoisestestapp',
    storageBucket: 'mindchoisestestapp.firebasestorage.app',
    iosBundleId: 'com.example.mindchoisesTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD9frbDlesnpCkfFKXiNC7x71iSPObUnU',
    appId: '1:345359008700:ios:ca8b0532f4c01f316a21b9',
    messagingSenderId: '345359008700',
    projectId: 'mindchoisestestapp',
    storageBucket: 'mindchoisestestapp.firebasestorage.app',
    iosBundleId: 'com.example.mindchoisesTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3dv7sDJosAJrC-1vFP_XbGaH_oGLoWFk',
    appId: '1:345359008700:web:f9db9aab344d79b16a21b9',
    messagingSenderId: '345359008700',
    projectId: 'mindchoisestestapp',
    authDomain: 'mindchoisestestapp.firebaseapp.com',
    storageBucket: 'mindchoisestestapp.firebasestorage.app',
    measurementId: 'G-LXKENY2NVD',
  );
}
